version: '3.2'
services:
  rabbitmq:
    image: rabbitmq:3.7.6-management
    container_name: rating-api_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 15672:15672
      - 5672:5672
